import Head from 'next/head'
import { supabase } from "../client"
import { useState, useEffect } from "react"
import { useRouter } from 'next/router'

export default function Home() {
  const [profile, setProfile] = useState(null)
  const [investmentData, setInvestmentData] = useState(null)
  const router = useRouter()
  useEffect(() => {
    fetchProfile()
  }, [])
  async function fetchProfile() {
    const profileData = await supabase.auth.user()
    if (!profileData) {
      router.push('/sign-in')
    } else {
      const investmentData = await fetchInvestorInfo(profileData.email);
      setProfile({ profileData, investmentData })
    }
  }

  const fetchInvestorInfo = async (email) => {
    const res = await fetch(`/api/investor/${email}`)
    // const res = await fetch(`/api/investor/rakesh@ascensionventures.com`)
    const data = await res.json();
    return data;
  }
  return (
    <div className="h-screen bg-gray-700 text-gray-100">
      <Head>
        <title>Ascension Investor Portal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-full w-full pt-32">
        {profile ? (
          <div>
            <h1 className="font-bold text-3xl mb-2">Welcome back, {profile.investmentData.investorDetails[0].name}</h1>
            <div id="fund-investments">
              <h3 className="font-bold text-2xl">Fund Investments</h3>
              <table className="mt-4 text-left table-auto w-full">
                <tr className="border-b-2 border-white-600">
                  <th>Fund</th>
                  <th>Type</th>
                  <th>Amount Invested</th>
                  <th>Current Value</th>
                  <th>Multiple</th>
                  <th>Balance to Deploy</th>
                </tr>
                {profile.investmentData.fundInvestments.map(fundInvestment => {
                  const { name, fund, invested, currentValue, multiple, type, balanceToDeploy } = fundInvestment;
                  return (<tr>
                    <td>{fund}</td>
                    <td>{type[0]}</td>
                    <td>£{invested.toLocaleString()}</td>
                    <td>£{currentValue.toLocaleString()}</td>
                    <td>{Math.round(multiple * 100) / 100}</td>
                    <td>{balanceToDeploy > 0 ? `£${balanceToDeploy.toLocaleString()}` : "£0"}</td>

                  </tr>)
                })}
              </table>
            </div>
          </div>

        ) : (<div id="sign-in-area">
          <h1 className="text-4xl font-bold">Ascension Investor Portal</h1>
        </div>)
        }
      </main >
    </div >
  )
}
